version: '3'
services:
  th-shopping-api:
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000 # 호스트 머신의 8000번 포트를 docker의 8000번 포트에 연결.
    environment:
      - WATCHFILES_FORCE_POLLING=true # 환경에 따라 핫 리로드를 위해 필요함. 
  db:
    image: mysql:8.0.41
    platform: linux/x86_64 # 애플 실리콘 맥(M1/M2 등)의 경우 필요
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' # root 계정 비밀번호 없이 생성
      MYSQL_DATABASE: 'shopping_app'
      TZ: 'Asia/Seoul'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password #MySQL8.0에서는 기본값이 "caching_sha2_password"이라 드라이버가 비지원이므로 변경
    ports:
      - 33306:3306 # 호스트머신이 33306번 포트를 docker의 3306번 포트에 연결
volumes:
  mysql_data: