"""product column  -add 등록자 정보(server_default)  컬럼

Revision ID: 3fc21259b2df
Revises: fc8d7c118cfa
Create Date: 2025-05-06 09:07:07.284247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc21259b2df'
down_revision: Union[str, None] = 'fc8d7c118cfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('th_products', sa.Column('created_user', sa.String(length=50), server_default=sa.text("'system'"), nullable=False, comment='등록자 - 아이디 정보 생성시 아이디+이름으로 표기 예정'))
    op.add_column('th_products', sa.Column('created_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='등록시각'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('th_products', 'created_datetime')
    op.drop_column('th_products', 'created_user')
    # ### end Alembic commands ###
