"""product column -add 가격

Revision ID: fc8d7c118cfa
Revises: d22db8f1a9ac
Create Date: 2025-05-06 08:51:03.767526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fc8d7c118cfa'
down_revision: Union[str, None] = 'd22db8f1a9ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('th_products', sa.Column('price', mysql.INTEGER(unsigned=True), nullable=False, comment='제품 가격'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('th_products', 'price')
    # ### end Alembic commands ###
