"""product table -add 신규

Revision ID: d22db8f1a9ac
Revises: 
Create Date: 2025-05-06 08:50:39.034298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd22db8f1a9ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('th_products',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='제품 테이블 Primary Key'),
    sa.Column('code', sa.String(length=8), nullable=False, comment='제품 고유 코드'),
    sa.Column('name', sa.String(length=30), nullable=False, comment='제품명'),
    sa.PrimaryKeyConstraint('id'),
    comment='제품 기본정보 테이블'
    )
    op.create_index(op.f('ix_th_products_code'), 'th_products', ['code'], unique=False)
    op.create_index(op.f('ix_th_products_name'), 'th_products', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_th_products_name'), table_name='th_products')
    op.drop_index(op.f('ix_th_products_code'), table_name='th_products')
    op.drop_table('th_products')
    # ### end Alembic commands ###
