"""product column  -add 삭제자  정보  컬럼

Revision ID: e94baf09de82
Revises: 56104eef9a07
Create Date: 2025-05-06 10:37:36.605394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e94baf09de82'
down_revision: Union[str, None] = '56104eef9a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('th_products', sa.Column('use_flag', mysql.TINYINT(display_width=1), nullable=False, comment='현재 판매 또는 사용중인 제품'))
    op.add_column('th_products', sa.Column('deleted_user', sa.String(length=50), nullable=True, comment='삭제자 - 아이디 정보 생성시 아이디+이름으로 표기 예정'))
    op.add_column('th_products', sa.Column('deleted_datetime', sa.DateTime(), nullable=True, comment='삭제시각'))
    op.alter_column('th_products', 'name',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_comment='제품명',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('th_products', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=30),
               existing_comment='제품명',
               existing_nullable=False)
    op.drop_column('th_products', 'deleted_datetime')
    op.drop_column('th_products', 'deleted_user')
    op.drop_column('th_products', 'use_flag')
    # ### end Alembic commands ###
