"""modify view_flag unsigned

Revision ID: 9db3511edfbd
Revises: 92b7b81a62e7
Create Date: 2025-05-14 13:34:34.046294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects.mysql import TINYINT

# revision identifiers, used by Alembic.
revision: str = '9db3511edfbd'
down_revision: Union[str, None] = '92b7b81a62e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'th_products',
        'use_flag',
        type_=TINYINT(1, unsigned=True),
        existing_type=TINYINT(1),
        nullable=False,
        existing_server_default=sa.text("'0'"),
        comment="현재 판매 또는 사용중인 제품"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'th_products',
        'use_flag',
        type_=TINYINT(1),  # unsigned 제거
        existing_type=TINYINT(1, unsigned=True),
        nullable=False,
        existing_server_default=sa.text("'0'"),
        comment="현재 판매 또는 사용중인 제품"
    )
    # ### end Alembic commands ###
