"""product column  -add 수정자  정보  컬럼

Revision ID: 56104eef9a07
Revises: 3fc21259b2df
Create Date: 2025-05-06 09:35:21.006559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56104eef9a07'
down_revision: Union[str, None] = '3fc21259b2df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('th_products', sa.Column('updated_user', sa.String(length=50), nullable=True, comment='수정자 - 아이디 정보 생성시 아이디+이름으로 표기 예정'))
    op.add_column('th_products', sa.Column('updated_datetime', sa.DateTime(), nullable=True, comment='수정시각'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('th_products', 'updated_datetime')
    op.drop_column('th_products', 'updated_user')
    # ### end Alembic commands ###
